DefaultContentLanguage = "pt"
baseurl = "https://example.com/"
disableLanguages = [""]
disqusShortname = ""
googleAnalytics = ""
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect-slim"
title = "HUE3"
[Languages.de]
LanguageCode = "de"
LanguageName = "Deutsche"
weight = 5
[Languages.en]
LanguageCode = "en"
LanguageName = "English"
weight = 1
[Languages.es]
LanguageCode = "es"
LanguageName = "Española"
weight = 6
[Languages.fr]
LanguageCode = "fr"
LanguageName = "Français"
description = "Un thème par HTML5 UP, porté par Julio Pescador. Simplifié et amélioré par Patrick Collins. Multilingue par StatnMap. Propulsé par Hugo."
title = "Hugo Future Imperfect Slim en français"
weight = 2
[[Languages.fr.menu.main]]
identifier = "home"
name = "Accueil"
pre = "<i class='fas fa-home'></i>"
url = "/"
weight = 1
[[Languages.fr.menu.main]]
identifier = "about"
name = "About"
pre = "<i class='far fa-id-card'></i>"
url = "/about/"
weight = 2
[[Languages.fr.menu.main]]
identifier = "blog"
name = "Blog"
pre = "<i class='far fa-newspaper'></i>"
url = "/blog/"
weight = 3
[[Languages.fr.menu.main]]
identifier = "categories"
name = "Catégories"
pre = "<i class='fas fa-sitemap'></i>"
url = "/categories/"
weight = 5
[[Languages.fr.menu.main]]
identifier = "contact"
name = "Contact"
pre = "<i class='far fa-envelope'></i>"
url = "/contact/"
weight = 6
[Languages.ja]
LanguageCode = "ja"
LanguageName = "日本語"
weight = 9
[Languages.pl]
LanguageCode = "pl"
LanguageName = "Polski"
description = "Motyw HTML5 UP, przeniesiony przez Julio Pescadora i wzbogacony przez Patricka Collinsa. Wielojęzyczny przez StatnMap. Zasilany przez Hugo."
title = "Hugo Future Imperfect Slim po polsku"
weight = 2
[[Languages.pl.menu.main]]
identifier = "home"
name = "Home"
pre = "<i class='fas fa-home'></i>"
url = "/"
weight = 1
[[Languages.pl.menu.main]]
identifier = "about"
name = "O mnie"
pre = "<i class='far fa-id-card'></i>"
url = "/about/"
weight = 2
[[Languages.pl.menu.main]]
identifier = "blog"
name = "Blog"
pre = "<i class='far fa-newspaper'></i>"
url = "/blog/"
weight = 3
[[Languages.pl.menu.main]]
identifier = "categories"
name = "Kategorie"
pre = "<i class='fas fa-sitemap'></i>"
url = "/categories/"
weight = 5
[[Languages.pl.menu.main]]
identifier = "contact"
name = "Kontakt"
pre = "<i class='far fa-envelope'></i>"
url = "/contact/"
weight = 6
[Languages.pt]
LanguageCode = "pt"
LanguageName = "Português"
description = "Um tema do HTML5 UP, portado por Julio Pescadora e reduzido por Patrick Collins. Multilíngue por StatnMap. Feito com Hugo."
title = "Hugo Future Imperfect Slim em português"
weight = 4
[[Languages.pt.menu.main]]
identifier = "home"
name = "Início"
pre = "<i class='fas fa-home'></i>"
url = "/"
weight = 1
[[Languages.pt.menu.main]]
identifier = "about"
name = "Sobre"
pre = "<i class='far fa-id-card'></i>"
url = "/about/"
weight = 2
[[Languages.pt.menu.main]]
identifier = "blog"
name = "Blog"
pre = "<i class='far fa-newspaper'></i>"
url = "/blog/"
weight = 3
[[Languages.pt.menu.main]]
identifier = "categories"
name = "Categorias"
pre = "<i class='fas fa-sitemap'></i>"
url = "/categories/"
weight = 5
[[Languages.pt.menu.main]]
identifier = "contact"
name = "Contato"
pre = "<i class='far fa-envelope'></i>"
url = "/contact/"
weight = 6
[Languages.zh-CN]
LanguageCode = "zh-CN"
LanguageName = "中文"
weight = 7
[Languages.zh-TW]
LanguageCode = "zh-TW"
LanguageName = "中文"
weight = 8
[[menu.main]]
identifier = "contact"
name = "Contact"
pre = "<i class='far fa-envelope'></i>"
url = "/contact/"
weight = 5
[[menu.main]]
identifier = "categories"
name = "Categories"
pre = "<i class='fas fa-sitemap'></i>"
url = "/categories/"
weight = 4
[[menu.main]]
identifier = "blog"
name = "Blog"
pre = "<i class='far fa-newspaper'></i>"
url = "/blog/"
weight = 3
[[menu.main]]
identifier = "about"
name = "About"
pre = "<i class='far fa-id-card'></i>"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class='fa fa-home'></i>"
url = "/"
weight = 1
[params]
cssFiles = ["default"]
enableCDN = false
highlightjs = true
highlightjsLang = ["html", "css", "js", "toml"]
highlightjsTheme = "github"
jsFiles = ["default"]
readingTime = true
socialShare = ["twitter", "facebook"]
viewMorePostsLink = "/blog/"
[params.footer]
rssFooter = false
socialFooter = true
[params.header]
dynamicTitles = true
languageMenu = true
navbarTitle = ">_ HUE3"
searchMenu = true
shareMenu = true
[params.intro]
alwaysOnHomepage = false
header = "HUE3"
hideWhenSingleColumn = false
paragraph = "Café sem açúcar, Feito é melhor que perfeito e WARNING não é ERRO !"
rssIntro = false
socialIntro = true
[params.intro.pic]
alt = "Hugo Future Imperfect Slim"
shape = "circle"
src = "/img/main/logo.jpg"
width = ""
[params.meta]
author = "Sias"
description = ""
favicon = false
faviconVersion = "1"
iOSColor = "#ffffff"
msColor = "#ffffff"
svg = true
[params.sidebar]
about = "Não importa quem somos ! O que realmente importa é lavar as mãos e ficar em casa...acompanhando nosso conteúdo, claro."
categories = true
categoriesByCount = true
postAmount = 5
[params.staticman]
api = ""
branch = ""
enabled = false
gitProvider = "github"
repo = ""
username = ""
[params.staticman.recaptcha]
encryptedKey = ""
siteKey = ""
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
facebook = "example"
foursquare = ""
github = "JonathanSias"
gitlab = ""
googleplus = ""
googlescholar = ""
instagram = "example"
jsfiddle = ""
medium = ""
orcid = ""
pinterest = "example"
qq = ""
quora = ""
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
tumblr = ""
twitter = "example"
vimeo = ""
vine = ""
wechat = ""
whatsapp = ""
wordpress = ""
xing = ""
youtube = ""
